name: uqdd-env
channels:
  - conda-forge
  - pytorch
  - defaults
  - rdkit
  - nvidia
dependencies:
  - python>=3.8
  - pip
  - notebook
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - tensorboard
  - tqdm
  - rdkit
  - ignite
  - pip:
      - chembl_webresource_client
      - https://github.com/OlivierBeq/Papyrus-scripts/tarball/master
      - uncertainty-toolbox
      - wandb
      - gpustat
      - onnx