name: uqdd-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
      - chembl_webresource_client
      - https://github.com/OlivierBeq/Papyrus-scripts/tarball/master
      - uncertainty-toolbox
      - sentencepiece
      - transformers
      - rdkit
      - wandb
      - jupyterlab
      - scipy
      - scikit-learn
      - scikit-posthocs
      - matplotlib
      - seaborn
      - plotly
      # Duplicate seaborn removed
      - pytest
      - tqdm
      - numpy
      - pandas
      - onnx
      - fastcluster
      - ankh
      - https://github.com/bolak92/bio-transformers/tarball/main
      - sentence-transformers
      - chembl-downloader
      - scienceplots
      - pingouin
      - mkdocs
      - mkdocs-material
      - mkdocstrings
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-plugin-tags
      - cmake
      - mapie
      - pandas-stubs