name: uqdd-env
channels:
  - conda-forge
  - pytorch
  - rdkit
  - nvidia
dependencies:
  - python=3.11
  - pip
  - cmake
  - mapie
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
      - chembl_webresource_client
      - https://github.com/OlivierBeq/Papyrus-scripts/archive/refs/tags/2.0.0.tar.gz
      - uncertainty-toolbox
      - transformers
      - rdkit
      - wandb
      - jupyterlab
      - scipy
      - scikit-learn
      - matplotlib
      - seaborn
      - plotly
      - seaborn
      - pytest
      - tqdm
      - numpy
      - pandas
      - onnx
      - fastcluster
      - ankh
      - https://github.com/bolak92/bio-transformers/tarball/main