name: uqdd-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - sentencepiece
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
      - chembl_webresource_client
      - https://github.com/OlivierBeq/Papyrus-scripts/tarball/master
      - uncertainty-toolbox
      - transformers
      - rdkit
      - wandb
      - jupyterlab
      - scipy
      - scikit-learn
      - scikit-posthocs
      - matplotlib
      - seaborn
      - plotly
      - pytest
      - tqdm
      - numpy
      - pandas
      - onnx
      - fastcluster
      - ankh
      - https://github.com/bolak92/bio-transformers/tarball/main
      - sentence-transformers
      - chembl-downloader
      - scienceplots
      - pingouin
      - mkdocs>=1.5.3
      - mkdocs-material==8.2.7
      - mkdocstrings==1.0.0
      - mkdocstrings-python==2.0.1
      - mkdocs-autorefs==1.4.3
      - mike==2.1.3
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-plugin-tags
      - cmake
      - mapie
      - pandas-stubs
      - setuptools
      - wheel
      - openpyxl
      - black
      - ruff
